from pathlib import Path

HISTORY_FILE = Path("harvest_history.json")
BRIX_THRESHOLD = 12.0
PRODUCTIVITY_THRESHOLD = 200.0
LOSS_THRESHOLD_FOR_OPERATOR = 15.0
LOSS_THRESHOLD = 10.0
TEMP_THRESHOLD = 35.0
MOIST_THRESHOLD = 20.0
MOIST_THRESHOLD_FOR_TEMP = 20.0
