-- Use the likely default PDB name for Oracle Free
ALTER SESSION SET CONTAINER = FREEPDB1;
 
-- Create the user
CREATE USER harvest_user IDENTIFIED BY "harvest_pass";
 
-- Grant necessary privileges
GRANT CONNECT, RESOURCE, CREATE SESSION, UNLIMITED TABLESPACE TO harvest_user;
 
-- Create the table under the harvest_user schema
CREATE TABLE harvest_user.harvest (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area NUMBER     NOT NULL,
  production NUMBER NOT NULL,
  loss_percentage NUMBER NOT NULL,
  lost_tonnage NUMBER,
  net_production NUMBER,
  productivity_per_hour NUMBER,
  productivity_per_hectare NUMBER,
  alert VARCHAR2(4000),
  recommendation VARCHAR2(4000),
  created_at DATE DEFAULT SYSDATE
);